# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VAMPSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAMPSwiftSample
  pod 'VAMP-SDK', '4.1.0.1'
  pod 'VAMPAdmobAdapter', '8.4.0.0'
  pod 'VAMPAppLovinAdapter', '10.0.1.0'
  pod 'VAMPFANAdapter', '6.3.0.0'
  pod 'VAMPMaioAdapter', '1.5.6.0'
  pod 'VAMPNendAdapter', '7.0.4.0'
  pod 'VAMPPangleAdapter', '3.4.2.8.0'
  pod 'VAMPTapjoyAdapter', '12.8.0.0'
  pod 'VAMPUnityAdsAdapter', '3.7.0.0'
end
