# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VAMPSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAMPSwiftSample
  pod 'VAMP-SDK', '4.1.1'
  pod 'VAMPAdmobAdapter', '8.5.0.0'
  pod 'VAMPAppLovinAdapter', '10.2.1.0'
  pod 'VAMPFANAdapter', '6.5.0.0'
  pod 'VAMPMaioAdapter', '1.5.8.0'
  pod 'VAMPNendAdapter', '7.0.5.0'
  pod 'VAMPPangleAdapter', '3.5.1.2.1'
  pod 'VAMPTapjoyAdapter', '12.8.1.0'
  pod 'VAMPUnityAdsAdapter', '3.7.1.0'
  pod 'VAMPLINEAdsAdapter', '2.3.20210326.1'
end
