# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VAMPSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAMPSwiftSample
  pod 'Google-Mobile-Ads-SDK', '8.1.0'
  pod 'AppLovinSDK', '6.15.2'
  pod 'NendSDK_iOS', '7.0.2'
  pod 'UnityAds', '3.6.0'
  pod 'FBAudienceNetwork', '6.2.1'
  pod 'MaioSDK', '1.5.6'
  pod 'TapjoySDK', '12.7.1'
  pod 'Bytedance-UnionAD', '3.3.6.2'
end
