# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'VAMPObjCSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAMPObjCSample
  pod 'VAMP-SDK'
  pod 'VAMPAdmobAdapter'
  pod 'VAMPIronSourceAdapter'
  pod 'VAMPLINEAdsAdapter'
  pod 'VAMPMaioAdapter'
  pod 'VAMPPangleAdapter'
  pod 'VAMPUnityAdsAdapter'
  pod 'VAMPAppLovinAdapter'
end
