# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VAMPObjCSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAMPObjCSample
  pod 'VAMP-SDK', '4.1.3'
  pod 'VAMPAdmobAdapter', '8.8.0.0'
  pod 'VAMPAppLovinAdapter', '10.3.4.0'
  pod 'VAMPFANAdapter', '6.5.1.0'
  pod 'VAMPMaioAdapter', '1.5.8.0'
  pod 'VAMPNendAdapter', '7.0.6.0'
  pod 'VAMPPangleAdapter', '3.8.1.0.0'
  pod 'VAMPTapjoyAdapter', '12.8.1.0'
  pod 'VAMPUnityAdsAdapter', '3.7.5.0'
  pod 'VAMPLINEAdsAdapter', '2.3.20210524.0'
end
