# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'VAMPObjCSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAMPObjCSample
  pod 'VAMP-SDK'
  pod 'VAMPAdmobAdapter'
  pod 'VAMPFANAdapter'
  pod 'VAMPMaioAdapter'
  pod 'VAMPNendAdapter'
  pod 'VAMPPangleAdapter'
  pod 'VAMPTapjoyAdapter'
  pod 'VAMPUnityAdsAdapter'
  pod 'VAMPLINEAdsAdapter'
end
